### PR TITLE
[WIP] Upgrade dependencies and migrate to Scala 2.13.3

### PR DESCRIPTION
**Pull request by ex0ns**
Hello ! 
As there were no updates on https://github.com/bot4s/telegram/pull/88 I wanted to start the migration, this is a draft and is open to discussion and comments.
I removed ScalaJS but we should be able to put it back after playing a bit with some dependencies (we need to bump to ScalaJS 1.0 I guess), the current settings is targeting 2.11, 2.12 and 2.13.

I'm having some VERY VERY strange compilation errors with the current state (in 2.13.2)

```
mill __.compile
[error] telegram/core/test/src/com/bot4s/telegram/api/CommandsSuite.scala:39:17: type mismatch;
[error]  found   : String("/hello")
[error]  required: com.bot4s.telegram.api.declarative.Command => ?
[error]       onCommand("/hello")(handlerHello)
[error]                 ^
[error] telegram/core/test/src/com/bot4s/telegram/api/CommandsSuite.scala:40:17: type mismatch;
[error]  found   : String("/helloWorld")
[error]  required: com.bot4s.telegram.api.declarative.Command => ?
[error]       onCommand("/helloWorld")(handlerHelloWorld)
[error]                 ^
[error] telegram/core/test/src/com/bot4s/telegram/api/CommandsSuite.scala:57:19: type mismatch;
[error]  found   : String("/cmd")
[error]  required: com.bot4s.telegram.api.declarative.Command => ?
[error]     bot.onCommand("/cmd")(handler)
[error]                   ^
[error] telegram/core/test/src/com/bot4s/telegram/api/CommandsSuite.scala:73:19: type mismatch;
[error]  found   : Symbol
[error]  required: com.bot4s.telegram.api.declarative.Command => ?
[error]     bot.onCommand('cmd)(handler)
[error]                   ^
```

This seems to be a implicit resolution issue, but I was not able to isolate and recreate the bug, and Intellij (with Implicits hints shows the correct values).
What is even stranger is that some tests ARE passing, for instance on line 39 and 40 there is an issue, but line 41 is fine:

```scala
      onCommand("/hello")(handlerHello)
      onCommand("/helloWorld")(handlerHelloWorld)
      onCommand("/respect" & RespectRecipient)(handlerRespect)
```

And 
``` bot.onCommand("/cmd")(handler)```
 seems to be an issue when ``` bot.onCommand("/cmd")(handler)``` is not...

I really don't understand what is happening right now, could some please try this locally, to check that this is not related to my setup.

Thanks

### CODE REVIEW

**Comment by XDracam** [comment]
I'm very interested in having this, thanks for your work.
I'll try to continue from where you left off, but I am by no means an expert.

**Comment by ex0ns** [comment]
I couldn't spend more time on this, but this lead me down a rabbit hole of a bug inside the scala-compiler, check https://github.com/scala/bug/issues/12070 

I think that one solution (I did not investigate) would be to drop the support of `Symbol` in this lib (those will be deprecated in Scala 3 anyway), and/or remove the implicit conversion from `string => Command`

**Comment by ex0ns** [comment]
@XDracam I did a quick fix for the issue described above, I didn't have the time to test it yet (I don't have any telegram token easily accessible right now), could you please pull the changes and try it

Thanks

**Comment by XDracam** [comment]
Wow, thanks for the response. Will do.

**Comment by XDracam** [comment]
I had to migrate the example bots and remove some slogging clutter.

Also, I don't think it's a good idea to make the conversions explicit, as that will drastically deteriorate the quality of the API. Instead, I renamed `onCommand(Filter[T])` to `onCommandWithFilter`. That did not break any example bots during compilation.

The random bot works fine now!

I'll continue to upgrade dependencies to newer versions where possible, run tests etc based on your version, and then I'll open a new PR. If that's fine by you.

**Pull request closed without merging**
