### PR TITLE
[examples] Add ZIO example

### PR DESCRIPTION
**Pull request by ex0ns**

### CODE REVIEW

**Comment by AlexGruPerm** [comment]
Is function .startPolling() in file Launcher.scala run Long Pooling bot mode?

If Yes, could you please provide example with weebhook (special with setting https context, maybe with
override def certificate
override val httpsContext
)

**Comment by ex0ns** [comment]
Unfortunately the webhook part (available inside the `akka` version of this library) is only compatible with Future (and not directly with Cats/ZIO unless you convert your IO/Task into a future first.

It might be possible to make this part tagless final as well and have another runtime next to the Akka one, but I never tried that and I will not have the time to investigate this very soon. 

If you wanted to try, I would start with the `Webhook` class that currently forces a `BotBase[Future]` and make it a 
```
trait Webhook[F[_]] extends WebRoutes with StrictLogging {
  this: BotBase[F] with BotExecutionContext with AkkaImplicits =>
```

But I don't know if this could work or not yet

**Comment by ex0ns** [comment]
Check the latest commit https://github.com/bot4s/telegram/pull/239/commits/ee12798dfe5520ae11e61c28b96ae2148b0cb952 to see an example of a webhook bot running on zio-http

**Comment by AlexGruPerm** [comment]
"Another idea I have is to re-implement the webhook handling for your specific use-case." - it's little bit difficult for me to understand. My level if fp small.

But this is a good news - "to see an example of a webhook bot running on zio-http" thanks a lot, I will investigate it in the coming days. Will return with feedback.

**Pull request merged**
